//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVFKManager.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SVFKManager.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Version]
        ///100=
        ///
        ///[SuppPath]
        ///data1=
        ///data2=
        ///data3=
        ///data4=
        ///data5=
        ///data6=
        ///data7=
        ///data8=
        ///
        ///[SuppCap]
        ///data1=
        ///data2=
        ///data3=
        ///data4=
        ///data5=
        ///data6=
        ///data7=
        ///data8=
        ///
        ///[Supp-Def-Mode]
        ///data1=1
        ///data2=1
        ///data3=1
        ///data4=1
        ///data5=1
        ///data6=1
        ///data7=1
        ///data8=1
        ///
        ///[SuppNum]
        ///data1=
        ///data2=
        ///data3=
        ///data4=
        ///data5=
        ///data6=
        ///data7=
        ///data8=
        ///
        ///[Supp-Start-Mode]
        ///data1=0
        ///data2=0
        ///data3=0
        ///data4=0
        ///data5=0
        ///data6=0
        ///data7=0
        ///data8=0.
        /// </summary>
        internal static string DefaultIni {
            get {
                return ResourceManager.GetString("DefaultIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Version]
        ///100=
        ///
        ///[SuppPath]
        ///data1=D:\Program Files\Okuma\Okuma EZ UI\EZ UI.exe
        ///data2=D:\Program Files\Okuma\Okuma THINC Startup Service\THINCStartupProcess.exe
        ///data3=D:\Program Files\Okuma\Okuma EZ UI\EZ UI.exe
        ///data4=D:\BLUM\BLUM Gauging Guide\Blum Gauging Guide.exe
        ///data5=D:\Program Files\Okuma\Okuma EZ UI\EZ UI.exe
        ///data6=D:\Program Files\Okuma\Okuma EZ UI\EZ UI.exe
        ///data7=D:\Program Files\Okuma\Okuma EZ UI\EZ UI.exe
        ///
        ///[SuppCap]
        ///data1=EZ UI
        ///data2=Startup\nSettings
        ///data3=EZ UI
        ///data4=Gauging\nGui [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FullIni {
            get {
                return ResourceManager.GetString("FullIni", resourceCulture);
            }
        }
    }
}
